version: "3.5"

services:
  proxy:
    image: traefik:latest
    command:
      - "--providers.docker.network=reverse_proxy_network"
      - "--providers.docker=true"
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.email=my@email.com
      - --certificatesresolvers.le.acme.storage=/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ./traefik/traefik.toml:/traefik.toml
      - ./volumes/traefik-acme:/acme # Tell Traefik to save SSL certs here
    networks:
      - proxy

networks:
  proxy:
    name: reverse_proxy_network