version: "3.5"

services:
  proxy:
    image: traefik:latest
    command:
      - --providers.docker.network=reverse_proxy_network
      - --providers.docker
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml
      - "./letsencrypt:/letsencrypt"
    networks:
      - proxy

networks:
  proxy:
    name: reverse_proxy_network