version: "3.5"

services:
  proxy:
    image: traefik:latest
    command:
      - "--providers.docker.network=reverse_proxy_network"
      - "--providers.docker=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"
    networks:
      - proxy

networks:
  proxy:
    name: reverse_proxy_network