version: "3.5"

services:
  reverse:
    container_name: proxy-traefik
    image: traefik:latest
    command:
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"

networks:
  default:
    external: true
    name: proxy