version: "3.5"

services:
  proxy:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      - "./traefik.yml:/traefik.yml:ro"
    networks:
      - proxy

networks:
  proxy:
    name: reverse_proxy_network