version: "3.5"

services:
  proxy:
    image: traefik:latest
    command:
      - "--providers.docker.network=reverse_proxy_network"
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --api.insecure
      - --certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.leresolver.acme.email=your@email.com
      - --certificatesresolvers.leresolver.acme.storage=/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ./traefik/traefik.toml:/traefik.toml
      - "./acme.json:/acme.json"
    networks:
      - proxy

networks:
  proxy:
    name: reverse_proxy_network