providers:
  docker:
    network: "reverse_proxy_network"

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: :443

certificatesResolvers:
  leresolver:
    acme:
      email: "nayte91@gmail.com"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web