experimental:
  http3: true

providers:
  docker:
    network: "reverse_proxy_network"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http3: {}

certificatesResolvers:
  leresolver:
    acme:
      email: "nayte91@gmail.com"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web