providers:
  docker:
    network: reverse_proxy_network

entryPoints:
  websecure:
    address: :443
    http:
      tls:
        certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      email: nayte91@gmail.com
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: ovh