entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# certificatesResolvers:
#   myresolver:
#     acme:
#       email: "nayte91@gmail.com"
#       storage: "letsencrypt/acme.json"
#       caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
#       tlsChallenge: